import { test, expect } from '@playwright/test';


/**
 * this code is generated by codegen tool
 */
test('ToDo Application', async ({ page }) => {
  await page.goto('http://10.103.0.190:7002/');
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('Check the Todos with Playwright');
  await page.getByTestId('text-input').press('Enter');
  await expect(page.getByTestId('todo-item-label')).toContainText('Check the Todos with Playwright');
  await expect(page.getByTestId('text-input')).toBeEmpty();
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('Add more to the list');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('Go back to home');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('footer-navigation').click();
  await expect(page.getByTestId('todo-list')).toContainText('Add more to the list');
  await page.getByText('Go back to home').click();
  await page.getByText('Go back to home').click();
  await expect(page.getByTestId('todo-list')).toContainText('Go back to home');
  await expect(page.getByTestId('footer-navigation')).toBeVisible();
  await page.getByRole('listitem').filter({ hasText: 'Add more to the list' }).getByTestId('todo-item-toggle').check();
  await expect(page.getByTestId('footer-navigation')).toMatchAriaSnapshot(`
    - link "Active":
      - /url: "#/active"
    `);
  await page.locator('body').click();
  await page.locator('html').click();
  await page.getByRole('listitem').filter({ hasText: 'Check the Todos with' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await expect(page.getByTestId('todo-list')).toMatchAriaSnapshot(`- text: Check the Todos with Playwright`);
  await expect(page.getByTestId('todo-list')).toMatchAriaSnapshot(`- text: Add more to the list`);
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByTestId('todo-item-button').click();
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('Happy coding');
  await page.getByTestId('text-input').press('Enter');
});