console.log(5 == '3'); // Output: false (numeric comparison)
console.log(5 === '3'); // Output: false (strict numeric comparison)
console.log(5 == '5'); // Output: true (numeric comparison)
console.log(5 === '5'); // Output: false (strict numeric comparison)
console.log(5 != '3'); // Output: true (numeric comparison)
console.log(5 !== '3'); // Output: true (strict numeric comparison)
console.log(5 != '5'); // Output: false (numeric comparison)
console.log(5 !== '5'); // Output: true (strict numeric comparison)

console.log(5 + "3"); // Output: "53" (string concatenation)
console.log(5 - "3"); // Output: 2 (numeric subtraction)
console.log(5 * "3"); // Output: 15 (numeric multiplication)
console.log(5 / "3"); // Output: 1.6666666666666667 (numeric division)
console.log(5 % "3"); // Output: 2 (numeric modulus)
console.log(5 + true); // Output: 6 (true is converted to 1)
console.log(5 + false); // Output: 5 (false is converted to 0)
console.log(5 + null); // Output: 5 (null is converted to 0)
console.log(5 + undefined); // Output: NaN (undefined cannot be converted to a number)      

console.log(5 + {}); // Output: "5[object Object]" (object is converted to string)  
console.log(5 + []); // Output: "5" (empty array is converted to empty string)
console.log(5 + [1, 2, 3]); // Output: "51,2,3" (array is converted to string)
console.log(5 + function() {}); // Output: "5function() {}" (function is converted to string)   
console.log(5 + Symbol("symbol")); // Output: TypeError: Cannot convert a Symbol value to a number
console.log(5 + new Date()); // Output: "5Mon Jun 10 2024 12:00:00 GMT+0000 (Coordinated Universal Time)" (date is converted to string)
console.log(5 + /regex/); // Output: "5/regex/" (regex is converted to string)
console.log(5 + new Map()); // Output: "5[object Map]" (map is converted to string)
console.log(5 + new Set()); // Output: "5[object Set]" (set is converted to string)


console.log(5 + NaN); // Output: NaN (NaN cannot be converted to a number)
console.log(5 + Infinity); // Output: Infinity (Infinity is a number)
console.log(5 + -Infinity); // Output: -Infinity (-Infinity is a number)
console.log(5 + 0); // Output: 5 (0 is a number)
console.log(5 + -0); // Output: 5 (-0 is a number)
console.log(5 + 1e+21); // Output: 1e+21 (1e+21 is a number)
console.log(5 + 1e-21); // Output: 5.000000000000001 (1e-21 is a number)
console.log(5 + 1.5); // Output: 6.5 (1.5 is a number)

